CREATE TABLE pos.products (
	id varchar NOT NULL,
	reference varchar NOT NULL,
	code varchar NOT NULL,
	codetype varchar NULL,
	"name" varchar NOT NULL,
	pricebuy float8 NOT NULL DEFAULT 0,
	pricesell float8 NOT NULL DEFAULT 0,
	category varchar NOT NULL,
	taxcat varchar NOT NULL,
	attributeset_id varchar NULL,
	stockcost float8 NOT NULL DEFAULT 0,
	stockvolume float8 NOT NULL DEFAULT 0,
	image bytea NULL,
	iscom bool NOT NULL DEFAULT false,
	isscale bool NOT NULL DEFAULT false,
	isconstant bool NOT NULL DEFAULT false,
	printkb bool NOT NULL DEFAULT false,
	sendstatus bool NOT NULL DEFAULT false,
	isservice bool NOT NULL DEFAULT false,
	"attributes" bytea NULL,
	display varchar NULL,
	isvprice bool NOT NULL DEFAULT false,
	isverpatrib bool NOT NULL DEFAULT false,
	texttip varchar NULL,
	warranty bool NOT NULL DEFAULT false,
	stockunits float8 NOT NULL DEFAULT 0,
	printto varchar NULL DEFAULT '1'::character varying,
	supplier varchar NULL,
	uom varchar NULL DEFAULT '0'::character varying,
	memodate timestamp NULL DEFAULT now(),
	node_id varchar(255) NULL,
	m_pricelist_version_id numeric(10) NULL,
	idempiere_id numeric NULL,
	ad_org_id numeric NULL,
	CONSTRAINT products_inx_0 UNIQUE (reference, node_id),
	CONSTRAINT products_inx_1 UNIQUE (code, node_id),
	CONSTRAINT products_pkey PRIMARY KEY (id),
	CONSTRAINT products_fk_1 FOREIGN KEY (category) REFERENCES pos.categories(id),
	CONSTRAINT products_taxcat_fk FOREIGN KEY (taxcat) REFERENCES pos.taxcategories(id)
);
CREATE UNIQUE INDEX products_attrset_fx ON pos.products USING btree (attributeset_id);