CREATE TABLE pos.bsca_paymentinstapago (
	deferre varchar NULL,
	code varchar NULL,
	cardholderidl varchar NULL,
	voucher varchar NULL,
	lote varchar NULL,
	description varchar NULL,
	cardline varchar NULL,
	tsi varchar NULL,
	commerce varchar NULL,
	datetime varchar NULL,
	ordernumber varchar NULL,
	id varchar NOT NULL,
	cardtype varchar NULL,
	idmerchant varchar NULL,
	responsecode varchar NULL,
	amount varchar NULL,
	approval varchar NULL,
	terminal varchar NULL,
	message varchar NULL,
	authid varchar NULL,
	arqc varchar NULL,
	tc varchar NULL,
	"sequence" varchar NULL,
	tvr varchar NULL,
	na varchar NULL,
	success varchar NULL,
	name varchar NULL,
	cardnumber varchar NULL,
	aid varchar NULL,
	bank varchar NULL,
	reference varchar NULL,
	orgvalue varchar NOT NULL,
	json varchar NULL,
	host varchar NULL,
	bsca_isimported bool NOT NULL DEFAULT false,
	CONSTRAINT bsca_paymentinstapago_pkey PRIMARY KEY (id, orgvalue,host)
);
